### ISSUE TITLE
putting it in minecraft

### ISSUE THREAD

**Issue by Goldencrator** [AgressiveBoy123/SeedCracker-1.17#1]
what thing do yuo download nothinhg is a far files i cant put it onto my mods folder pls help

**Comment by Roxxdotexe** [comment]
https://github.com/AgressiveBoy123/SeedCracker-1.17/releases

**Comment by Goldencrator** [comment]
> https://github.com/AgressiveBoy123/SeedCracker-1.17/releases

i did that but it says its a virus and i cant download it

**Comment by Roxxdotexe** [comment]
just disable antivirus ant put .jar in mods folder and it will be ok

**Comment by Roxxdotexe** [comment]
> > https://github.com/AgressiveBoy123/SeedCracker-1.17/releases
> 
> i did that but it says its a virus and i cant download it

just disable antivirus ant put .jar in mods folder and it will be ok

**Comment by kaan1957** [comment]
Can't believe people are using my plugins. I was doing it for fun actually, but if you guys are having trouble with it, listen carefully. First of all you need to install Fabric API. Then, you'll just put seedcracker.jar file in the mods folder located in appdata.
