### ISSUE TITLE
1.18 support

### ISSUE THREAD

**Issue by GaspardCulis** [AgressiveBoy123/SeedCracker-1.17#4]
Hey , nice seed cracker , but could you pleaaase update it so that it works for 1.18 ?

Cheers

**Comment by kaan1957** [comment]
I don't think I can do that anymore since KaptainWutax stopped releasing new seed crackers for 1.18 and I doubt he never will because seeds are going to change entirely. You should wait for someone to do it because I don't think I'll be able to do it
